# Generated by Django 5.1.5 on 2025-02-21 14:47

from django.db import migrations, models
from uuid import UUID

class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='uuid',
            field=models.UUIDField(default=UUID("00000000-0000-0000-0000-000000000000", version=4), unique=True),
            preserve_default=False,
        ),
    ]
