# Generated by Django 5.1.7 on 2025-03-11 17:38

from uuid import UUID
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coreapp", "0002_alter_device_uuid_alter_metric_uuid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reading",
            name="device",
        ),
        migrations.AddField(
            model_name="metric",
            name="device",
            field=models.ForeignKey(
                default=UUID("2f4c5745-c06a-4f35-977c-773c621170be"),
                on_delete=django.db.models.deletion.CASCADE,
                to="coreapp.device",
            ),
            preserve_default=False,
        ),
    ]
