# Generated by Django 5.1.7 on 2025-03-07 17:28

from uuid import UUID
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coreapp", "0002_device_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="metric",
            name="uuid",
            field=models.UUIDField(default=UUID("00000000-0000-0000-0000-000000000000", version=4), unique=True),
            preserve_default=False,
        ),
    ]
